Add-new-exam-page
assafnoahkoren/quiz-app pull request #5
Opened 2024-05-22 17:53 UTC by idan0540

2024-05-30 23:06 UTC, assafnoahkoren requested changes

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/hooks/useGlobalColor.ts
> +export default useGlobalColor;
What makes this function a hook?

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/hooks/useGlobalColor.ts
> +  const subjectId = localStorage.getItem("selectedSubjectId");
we have the selectedSubject in the datastore, can't we use it here and avoid two sources of truth?

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/App.tsx
> +  useGlobalColor();
Why you chose to use this `useGlobalColor()` inside the App component and not outside of it (at line 19 for example)

```suggestion
useGlobalColor();
const App = () => {

```

Its more of a thought experiment than an actual problem.

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.scss
> +    }
lets create a ThemeStore and manage all the colors, what do you say?
This would make it super easy to create dark mode and manage colors

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.tsx
> +        <div className="correct-answers" style={{ flex: firstNum / total }}>
Cool use of the flex css property! 👏

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.scss
> +    font-size: 1.2em;
Thought exercise: what is the 'em' measurement?

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.scss
> +        padding: 5px 1px;
```suggestion
        padding: 5px 10px;
```

I find it looking better for low values (if firstNum is '1' this part looks smooshed with padding 1px )

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.scss
> +        padding: 5px 1px;
![image](https://github.com/assafnoahkoren/quiz-app/assets/16115480/9713d6ff-a8f4-4b2f-ad8c-5e96a82b28e5)

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ScoresChart.tsx
> +const ScoresChart: React.FC<ScoresChartProps> = ({
Please add the labels too:
![image](https://github.com/assafnoahkoren/quiz-app/assets/16115480/5b865c40-0a89-46e5-b7a3-e83250a976a2)

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/ToggleOption.tsx
> +const ToggleOption: React.FC<ToggleOptionProps> = ({ children }) => {
Im not use this component is needed.
A toggle is basically `<input type="checkbox"/>
`

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/navbar/Navbar.tsx
>        {authStore.isLogged && (
You dont have to repeat 'navbar' class twice
```suggestion
  const navbarClass = authStore.isLogged ? "logged" : "";
  return (
    <div className={`navbar ${navbarClass}`}>
      {authStore.isLogged && (
```

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/subject/SubjectCard.tsx
> +  let backgroundColor = localStorage.getItem(props.id);
I think we should move that logic to a ThemeStore

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/subject/SubjectOption.tsx
> +// the observer shouldnt listen and render after any change?
The point of useEffect is to reduce the amount of code the component will run when it rerenders.
if you have [] as the dependencies array it will run only once. When you add dataStore.isSearching to the dependencies array it will run the code when dataStore.isSearching changes.

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/subject/SubjectOption.tsx
> +      console.log(dataStore.isSearching);
remove

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/stores/DataStore.ts
> +    console.log(filter);
remove

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/stores/DataStore.ts
> +    console.log(this.subjects);
remove

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/components/UIElements/Search.scss
> +}
super specific to your screen size. please replace with responsive layout.
![image](https://github.com/assafnoahkoren/quiz-app/assets/16115480/0dba2ca0-f9d5-4811-b73e-569b9371b717)

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/pages/Login.tsx
> +      <div className="page-wrapper">
Not sure if this line caused it but can you center the login layout?
![image](https://github.com/assafnoahkoren/quiz-app/assets/16115480/8bedf0ac-fa62-4044-8b59-2032f72dcc62)

2024-05-30 23:06 UTC, assafnoahkoren commented on client/src/pages/NewExam.tsx
> +      </div>
We are gonna replace this with a Form, I will create a task for that

2024-06-01 22:36 UTC, assafnoahkoren approved these changes

2024-06-02 13:24 UTC, idan0540 commented on client/src/App.tsx
> +  useGlobalColor();
to use it anytime the page is refreshed and the app is rerenderd, it is not the right approach?

2024-06-02 13:28 UTC, merged